import * as WailsApp from '../../wailsjs/go/main/App';

export const wailsAdapter = {
  name: 'wails',
  selectDocumentDir: () => WailsApp.SelectDocumentDir(),
  listDocuments: dir => WailsApp.ListDocuments(dir),
  listDocumentTree: dir => WailsApp.ListDocumentTree(dir),
  readDocument: path => WailsApp.ReadDocument(path),
  readImageAsset: (documentPath, imageDir, source) => WailsApp.ReadImageAsset(documentPath, imageDir, source),
  writeDocument: (path, content) => WailsApp.WriteDocument(path, content),
  writeImageAsset: (documentPath, imageDir, fileName, data) => WailsApp.WriteImageAsset(documentPath, imageDir, fileName, data),
  createDocument: (dir, name) => WailsApp.CreateDocument(dir, name),
  deleteDocument: path => WailsApp.DeleteDocument(path),
  listRecycleBin: limit => WailsApp.ListRecycleBin(limit),
  restoreRecycleItem: id => WailsApp.RestoreRecycleItem(id),
  purgeRecycleItem: id => WailsApp.PurgeRecycleItem(id),
  renameDocument: (path, name) => WailsApp.RenameDocument(path, name),
  revealDocument: path => WailsApp.RevealDocument(path),
  openDocumentFile: () => WailsApp.OpenDocumentFile(),
  acceptDroppedDocument: path => WailsApp.AcceptDroppedDocument(path),
  acceptBrowserDroppedDocument: async () => null,
  saveDocumentAs: content => WailsApp.SaveDocumentAs(content),
  saveExportFile: (defaultName, content, encoding) => WailsApp.SaveExportFile(defaultName, content, encoding),
  addRecentFile: (path, name) => WailsApp.AddRecentFile(path, name),
  listRecentFiles: limit => WailsApp.ListRecentFiles(limit),
  getAppState: () => WailsApp.GetAppState(),
  getAppVersion: () => WailsApp.GetAppVersion(),
  getApplicationIconContentRatio: () => WailsApp.GetApplicationIconContentRatio(),
  saveAppSetting: (key, value) => WailsApp.SaveAppSetting(key, value),
  loadAppSettings: () => WailsApp.LoadAppSettings(),
  getThemesDirectory: () => WailsApp.GetThemesDirectory(),
  listUserThemes: () => WailsApp.ListUserThemes(),
  saveUserTheme: (id, content) => WailsApp.SaveUserTheme(id, content),
  deleteUserTheme: id => WailsApp.DeleteUserTheme(id),
  revealThemesDirectory: () => WailsApp.RevealThemesDirectory(),
  getUserPluginsDirectory: () => WailsApp.GetUserPluginsDirectory(),
  listUserPlugins: () => WailsApp.ListUserPlugins(),
  saveUserPlugin: (id, content) => WailsApp.SaveUserPlugin(id, content),
  deleteUserPlugin: id => WailsApp.DeleteUserPlugin(id),
  revealUserPluginsDirectory: () => WailsApp.RevealUserPluginsDirectory(),
  saveRecoveryState: payload => WailsApp.SaveRecoveryState(payload),
  loadRecoveryState: () => WailsApp.LoadRecoveryState(),
  clearRecoveryState: () => WailsApp.ClearRecoveryState(),
  setApplicationIcon: dataURL => WailsApp.SetApplicationIcon(dataURL),
  setPendingChanges: (count, summary) => WailsApp.SetPendingChanges(count, summary),
  confirmClose: () => WailsApp.ConfirmClose(),
};
