export const state = {
  docDir: '',
  docs: [],
  docTree: [],
  expandedDirs: new Set(),
  currentDoc: null,
  currentContent: '',
  persistedContent: '',
  selection: null,
  selectionIndex: null,
  lastCompositionTransaction: null,
  editorSession: null,
  suppressNextInput: false,
  isDirty: false,
  isEditor: false,
  sourceMode: false,
  view: 'editor',
  sidebarWidth: 250,
  sidebarCollapsed: false,
  homeRecentWidth: 330,
};
