// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptDroppedDocument(arg1) {
  return window['go']['main']['App']['AcceptDroppedDocument'](arg1);
}

export function AddRecentFile(arg1, arg2) {
  return window['go']['main']['App']['AddRecentFile'](arg1, arg2);
}

export function ClearRecoveryState() {
  return window['go']['main']['App']['ClearRecoveryState']();
}

export function ConfirmClose() {
  return window['go']['main']['App']['ConfirmClose']();
}

export function CreateDocument(arg1, arg2) {
  return window['go']['main']['App']['CreateDocument'](arg1, arg2);
}

export function DeleteDocument(arg1) {
  return window['go']['main']['App']['DeleteDocument'](arg1);
}

export function DeleteUserPlugin(arg1) {
  return window['go']['main']['App']['DeleteUserPlugin'](arg1);
}

export function DeleteUserTheme(arg1) {
  return window['go']['main']['App']['DeleteUserTheme'](arg1);
}

export function GetAppState() {
  return window['go']['main']['App']['GetAppState']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetApplicationIconContentRatio() {
  return window['go']['main']['App']['GetApplicationIconContentRatio']();
}

export function GetThemesDirectory() {
  return window['go']['main']['App']['GetThemesDirectory']();
}

export function GetUserPluginsDirectory() {
  return window['go']['main']['App']['GetUserPluginsDirectory']();
}

export function ListDocumentTree(arg1) {
  return window['go']['main']['App']['ListDocumentTree'](arg1);
}

export function ListDocuments(arg1) {
  return window['go']['main']['App']['ListDocuments'](arg1);
}

export function ListRecentFiles(arg1) {
  return window['go']['main']['App']['ListRecentFiles'](arg1);
}

export function ListRecycleBin(arg1) {
  return window['go']['main']['App']['ListRecycleBin'](arg1);
}

export function ListUserPlugins() {
  return window['go']['main']['App']['ListUserPlugins']();
}

export function ListUserThemes() {
  return window['go']['main']['App']['ListUserThemes']();
}

export function LoadAppSettings() {
  return window['go']['main']['App']['LoadAppSettings']();
}

export function LoadRecoveryState() {
  return window['go']['main']['App']['LoadRecoveryState']();
}

export function MenuSave() {
  return window['go']['main']['App']['MenuSave']();
}

export function MenuSaveAs() {
  return window['go']['main']['App']['MenuSaveAs']();
}

export function OpenDocumentFile() {
  return window['go']['main']['App']['OpenDocumentFile']();
}

export function PurgeRecycleItem(arg1) {
  return window['go']['main']['App']['PurgeRecycleItem'](arg1);
}

export function ReadDocument(arg1) {
  return window['go']['main']['App']['ReadDocument'](arg1);
}

export function ReadImageAsset(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReadImageAsset'](arg1, arg2, arg3);
}

export function RememberWindowSize() {
  return window['go']['main']['App']['RememberWindowSize']();
}

export function RenameDocument(arg1, arg2) {
  return window['go']['main']['App']['RenameDocument'](arg1, arg2);
}

export function RestoreRecycleItem(arg1) {
  return window['go']['main']['App']['RestoreRecycleItem'](arg1);
}

export function RevealDocument(arg1) {
  return window['go']['main']['App']['RevealDocument'](arg1);
}

export function RevealThemesDirectory() {
  return window['go']['main']['App']['RevealThemesDirectory']();
}

export function RevealUserPluginsDirectory() {
  return window['go']['main']['App']['RevealUserPluginsDirectory']();
}

export function SaveAppSetting(arg1, arg2) {
  return window['go']['main']['App']['SaveAppSetting'](arg1, arg2);
}

export function SaveDocumentAs(arg1) {
  return window['go']['main']['App']['SaveDocumentAs'](arg1);
}

export function SaveExportFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveExportFile'](arg1, arg2, arg3);
}

export function SaveRecoveryState(arg1) {
  return window['go']['main']['App']['SaveRecoveryState'](arg1);
}

export function SaveUserPlugin(arg1, arg2) {
  return window['go']['main']['App']['SaveUserPlugin'](arg1, arg2);
}

export function SaveUserTheme(arg1, arg2) {
  return window['go']['main']['App']['SaveUserTheme'](arg1, arg2);
}

export function SelectDocumentDir() {
  return window['go']['main']['App']['SelectDocumentDir']();
}

export function SetApplicationIcon(arg1) {
  return window['go']['main']['App']['SetApplicationIcon'](arg1);
}

export function SetPendingChanges(arg1, arg2) {
  return window['go']['main']['App']['SetPendingChanges'](arg1, arg2);
}

export function WindowSize() {
  return window['go']['main']['App']['WindowSize']();
}

export function WriteDocument(arg1, arg2) {
  return window['go']['main']['App']['WriteDocument'](arg1, arg2);
}

export function WriteImageAsset(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['WriteImageAsset'](arg1, arg2, arg3, arg4);
}
